Table Sections {
    id int [pk, increment, ref: > Attraction.id]
    name string
    attractionId int
}

Table Attraction {
    id int [pk, ref: > Guests.attractionId]
    name string
    
}

Table Services {
    id int [pk, ref: > Guests.servicesId]
    name string
    
    
}

Table Guests {
    id int [pk, increment]
    firstName string
    lastName string
    attractionId int
    servicesId int
}

