const database = {
  Sections: [
    { id: 101, name: "Northeast", attractionsID: 501 },
    { id: 102, name: "North", attractionsID: 502 },
    { id: 103, name: "Northwest", attractionsID: [503, 504, 505] },
    { id: 104, name: "Southwest", attractionsID: 506 },
    { id: 105, name: "South", attractionsID: [507, 508, 509] },
    { id: 106, name: "Southeast", attractionsID: [510, 511] },
  ],
  Attractions: [
    { id: 501, name: "Chamfort River" },
    { id: 502, name: "Lost Wolf Hiking Trail" },
    { id: 503, name: "Lodge" },
    { id: 504, name: "Hotel" },
    { id: 505, name: "Restaurant" },
    { id: 506, name: "Gander River (Natural Preserve)" },
    { id: 507, name: "Campgrounds" },
    { id: 508, name: "Office Park" },
    { id: 509, name: "Children Play Areas" },
    { id: 510, name: "Pine Bluffs Trails (Non Beginner)" },
    { id: 511, name: "Pine Bluffs Trails (Beginner)" },
  ],
  Services: [
    { id: 1, name: "Rafting" },
    { id: 2, name: "Canoeing" },
    { id: 3, name: "Fishing" },
    { id: 4, name: "Hiking" },
    { id: 5, name: "Picknicking" },
    { id: 6, name: "Rock Climbing" },
    { id: 7, name: "Lodging" },
    { id: 8, name: "Parking" },
    { id: 9, name: "Information" },
    { id: 10, name: "Zip Lines" },
    { id: 11, name: "Food Vendors" },
  ],
  Guests: [
    {
      id: 1,
      firstname: "Mike",
      lastname: "Brown",
      attractionID: 509,
      servicesID: 8,
    },
    {
      id: 2,
      firstname: "Alice",
      lastname: "Taylor",
      attractionID: 507,
      servicesID: 7,
    },
    {
      id: 3,
      firstname: "Rachel",
      lastname: "White",
      attractionID: 503,
      servicesID: 5,
    },
    {
      id: 4,
      firstname: "John",
      lastname: "Davis",
      attractionID: 511,
      servicesID: 10,
    },
    {
      id: 5,
      firstname: "Laura",
      lastname: "Martinez",
      attractionID: 501,
      servicesID: 1,
    },
    {
      id: 6,
      firstname: "Nancy",
      lastname: "Lopez",
      attractionID: 510,
      servicesID: 5,
    },
    {
      id: 7,
      firstname: "Oliver",
      lastname: "Rodriguez",
      attractionID: 506,
      servicesID: 3,
    },
    {
      id: 8,
      firstname: "Frank",
      lastname: "Anderson",
      attractionID: 502,
      servicesID: 6,
    },
    {
      id: 9,
      firstname: "Isaac",
      lastname: "Hernandez",
      attractionID: 504,
      servicesID: 7,
    },
    {
      id: 10,
      firstname: "Karen",
      lastname: "Smith",
      attractionID: 505,
      servicesID: 5,
    },
    {
      id: 11,
      firstname: "Charlie",
      lastname: "Moore",
      attractionID: 503,
      servicesID: 7,
    },
    {
      id: 12,
      firstname: "Eve",
      lastname: "Garcia",
      attractionID: 502,
      servicesID: 4,
    },
    {
      id: 13,
      firstname: "Paul",
      lastname: "Brown",
      attractionID: 506,
      servicesID: 4,
    },
    {
      id: 14,
      firstname: "Diana",
      lastname: "Miller",
      attractionID: 508,
      servicesID: 8,
    },
    {
      id: 15,
      firstname: "Quincy",
      lastname: "Taylor",
      attractionID: 507,
      servicesID: 9,
    },
    {
      id: 16,
      firstname: "Bob",
      lastname: "Davis",
      attractionID: 510,
      servicesID: 10,
    },
    {
      id: 17,
      firstname: "Rachel",
      lastname: "Jones",
      attractionID: 505,
      servicesID: 5,
    },
    {
      id: 18,
      firstname: "John",
      lastname: "Rodriguez",
      attractionID: 511,
      servicesID: 4,
    },
    {
      id: 19,
      firstname: "Nancy",
      lastname: "Johnson",
      attractionID: 501,
      servicesID: 2,
    },
    {
      id: 20,
      firstname: "Mike",
      lastname: "Anderson",
      attractionID: 509,
      servicesID: 8,
    },
    {
      id: 21,
      firstname: "Jack",
      lastname: "Lopez",
      attractionID: 503,
      servicesID: 8,
    },
    {
      id: 22,
      firstname: "Alice",
      lastname: "Martinez",
      attractionID: 507,
      servicesID: 7,
    },
    {
      id: 23,
      firstname: "Henry",
      lastname: "White",
      attractionID: 502,
      servicesID: 5,
    },
    {
      id: 24,
      firstname: "Isaac",
      lastname: "Hernandez",
      attractionID: 506,
      servicesID: 3,
    },
    {
      id: 25,
      firstname: "Oliver",
      lastname: "Garcia",
      attractionID: 510,
      servicesID: 4,
    },
    {
      id: 26,
      firstname: "Karen",
      lastname: "Thompson",
      attractionID: 504,
      servicesID: 7,
    },
    {
      id: 27,
      firstname: "Grace",
      lastname: "Taylor",
      attractionID: 505,
      servicesID: 5,
    },
    {
      id: 28,
      firstname: "Diana",
      lastname: "Williams",
      attractionID: 508,
      servicesID: 8,
    },
    {
      id: 29,
      firstname: "Paul",
      lastname: "Brown",
      attractionID: 501,
      servicesID: 3,
    },
    {
      id: 30,
      firstname: "Laura",
      lastname: "Smith",
      attractionID: 511,
      servicesID: 11,
    },
    {
      id: 31,
      firstname: "Eve",
      lastname: "Johnson",
      attractionID: 509,
      servicesID: 8,
    },
    {
      id: 32,
      firstname: "Bob",
      lastname: "Lopez",
      attractionID: 506,
      servicesID: 4,
    },
    {
      id: 33,
      firstname: "Quincy",
      lastname: "Martinez",
      attractionID: 502,
      servicesID: 6,
    },
    {
      id: 34,
      firstname: "Jack",
      lastname: "Davis",
      attractionID: 503,
      servicesID: 9,
    },
    {
      id: 35,
      firstname: "Charlie",
      lastname: "Thompson",
      attractionID: 507,
      servicesID: 8,
    },
    {
      id: 36,
      firstname: "Rachel",
      lastname: "Rodriguez",
      attractionID: 510,
      servicesID: 5,
    },
    {
      id: 37,
      firstname: "Mike",
      lastname: "Taylor",
      attractionID: 501,
      servicesID: 1,
    },
    {
      id: 38,
      firstname: "Nancy",
      lastname: "Garcia",
      attractionID: 504,
      servicesID: 7,
    },
    {
      id: 39,
      firstname: "John",
      lastname: "Anderson",
      attractionID: 505,
      servicesID: 5,
    },
    {
      id: 40,
      firstname: "Alice",
      lastname: "Brown",
      attractionID: 508,
      servicesID: 8,
    },
  ],
};

export const getSections = () => {
  return structuredClone(database.Sections);
};

export const getAttractions = () => {
  return structuredClone(database.Attractions);
};

export const getServices = () => {
  return structuredClone(database.Services);
};

export const getGuests = () => {
  return structuredClone(database.Guests);
};
